config/routes.rb
Rails.application.routes.draw do
  resources :calories
  devise_for :users, :controllers => {:registrations => "my_devise/registrations"}
  get '/documentation', to: 'home#documentation'
  get '/dashboard', to: 'home#dashboard'
  get '/sharedp', to: 'home#shared_progress'
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calory.rb
class Calory < ApplicationRecord
  belongs_to :user
  default_scope -> { order(date: :desc) }
  scope :created_between, lambda {|start_date, end_date| where("date >= ? AND date <= ?", start_date, end_date )}
  paginates_per 10
  validates :user_id, presence: true
  validates :comment, presence: true
  validates :calories_ingested, presence: true, numericality: true
  validates :calories_burned, presence: true, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :calories, dependent: :destroy

  def age
    now = Time.now.utc.to_date
    now.year - birthday.year - (birthday.to_date.change(:year => now.year) > now ? 1 : 0)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def imc
    weight / (height**2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      attributes = [:first_name, :last_name, :birthday, :weight, :avatar, :height]
      devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
      devise_parameter_sanitizer.permit(:account_update, keys: attributes)
    end

    def after_sign_in_path_for(resource)
        return root_path
    end

    def after_sign_out_path_for(resource)
        return root_path
    end
end

app/controllers/calories_controller.rb
class CaloriesController < ApplicationController
  before_action :set_calory, only: %i[ show edit update destroy ]

  # GET /calories or /calories.json
  def index
    if user_signed_in?
      if !params[:comment].blank? || (!params[:date_start].blank? && !params[:date_end].blank?)
        puts 'entroooo'
        @calories = Calory.where(user_id: current_user.id)
        if !params[:comment].blank?
          @calories = @calories.where("comment like ?","%#{params[:comment]}%")
        end
        if !params[:date_start].blank? && !params[:date_end].blank?
          @calories = @calories.created_between(params[:date_start], params[:date_end])
        end
        @calories = @calories.page params[:page]
      else
        @calories = Calory.where(user_id: current_user.id).page params[:page]
      end
    else
      redirect_to user_session_path
    end
  end

  # GET /calories/1 or /calories/1.json
  def show
  end

  # GET /calories/new
  def new
    if user_signed_in?
      @calory = Calory.new
    else
      redirect_to user_session_path
    end
  end

  # GET /calories/1/edit
  def edit
  end

  # POST /calories or /calories.json
  def create
    @calory = Calory.new(calory_params)

    respond_to do |format|
      if @calory.save
        format.html { redirect_to calory_url(@calory), notice: "Calory was successfully created." }
        format.json { render :show, status: :created, location: @calory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @calory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calories/1 or /calories/1.json
  def update
    respond_to do |format|
      if @calory.update(calory_params)
        format.html { redirect_to calory_url(@calory), notice: "Calory was successfully updated." }
        format.json { render :show, status: :ok, location: @calory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @calory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calories/1 or /calories/1.json
  def destroy
    @calory.destroy

    respond_to do |format|
      format.html { redirect_to calories_url, notice: "Calory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calory
      @calory = Calory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def calory_params
      params.require(:calory).permit(:calories_ingested, :calories_burned, :comment, :date, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ApplicationHelper
  def index
  end
  def dashboard
    auth = params[:auth_code]
    if user_signed_in?
      @user = current_user
      @data = [
        {name: "calories_ingested", data: Calory.unscoped.group_by_day(:date, range: 4.weeks.ago.midnight..Time.now).where(user_id: current_user.id).sum(:calories_ingested)},
        {name: "calories_burned", data: Calory.unscoped.group_by_day(:date, range: 4.weeks.ago.midnight..Time.now).where(user_id: current_user.id).sum(:calories_burned)}
      ]
    elsif !auth.blank?
      auth1 = cipher_cesar(auth, 5, -1)
      @user = User.find_by(email:auth1)
      if @user == nil
        redirect_to root_path
      else
        @data = [
          {name: "calories_ingested", data: Calory.unscoped.group_by_day(:date, range: 4.weeks.ago.midnight..Time.now).where(user_id: @user.id).sum(:calories_ingested)},
          {name: "calories_burned", data: Calory.unscoped.group_by_day(:date, range: 4.weeks.ago.midnight..Time.now).where(user_id: @user.id).sum(:calories_burned)}
        ]
      end

    else
      redirect_to user_session_path
    end

  end
  def documentation
  end
  def shared_progress
    email = params[:email]
    @user = current_user
    if !email.blank?
      flash[:notice] =  "Email was successfully sent."
      token = cipher_cesar(@user.email, 5 )
      SharedProgressMailer.with(email: email, user: @user, token: token).shared_email.deliver_now
    end
  end
end

app/controllers/my_devise/registrations_controller.rb
class MyDevise::RegistrationsController < Devise::RegistrationsController
    protected 
    def after_update_path_for(resource)
        edit_user_registration_path(resource)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    $alfabeto_mayusculas = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    $alfabeto_minusculas = "abcdefghijklmnopqrstuvwxyz"
    $longitud_alfabeto = 26
    $limite_inferior_mayusculas = 65
    $limite_inferior_minusculas = 97
    def cipher_cesar(string_email, rotation, orientation = 1)
        chain_with_rotation = ""
        for letra in string_email.chars
            if !letra.match(/^[[:alpha:]]$/)
                chain_with_rotation += letra
                next
            end
            alfabeto = $alfabeto_mayusculas
            limite = $limite_inferior_mayusculas
            if letra == letra.downcase
                alfabeto = $alfabeto_minusculas
                limite = $limite_inferior_minusculas
            end

            valor_ascii = letra.ord
            rotation_verdaderas = rotation * orientation
            nueva_posicion = (valor_ascii - limite + rotation_verdaderas) % $longitud_alfabeto
            chain_with_rotation += alfabeto[nueva_posicion]
        end
        chain_with_rotation
    end
end

app/helpers/calories_helper.rb
module CaloriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/calories/_form.html.erb
<%= form_with(model: calory) do |form| %>
  <% if calory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(calory.errors.count, "error") %> prohibited this calory from being saved:</h2>

      <ul>
        <% calory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :calories_ingested %>
    <%= form.text_field :calories_ingested, :class => "input is-info is-rounded" %>
  </div>

  <div class="field">
    <%= form.label :calories_burned %>
    <%= form.text_field :calories_burned, :class => "input is-info is-rounded" %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, :class => "textarea is-info is-rounded" %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_field :date, as: :date_time_picker, :class => "input is-info is-rounded" %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Calory', :class => 'button is-primary' %>
  </div>

<% end %>

app/views/calories/edit.html.erb
<div class="columns content has-text-centered">
<div class="column"></div>
<div class="column is-one-third">
<h1>Editing Calory</h1>

<%= render 'form', calory: @calory %>

<%= link_to 'Show', @calory %> |
<%= link_to 'Back', calories_path %>
</div>
<div class="column"></div>
</div>

app/views/calories/index.html.erb
<div class="has-text-centered">
<%= form_tag "/calories", method: "GET" do %>
  <%= label_tag :comment %>
  <%= text_field_tag :comment, params[:comment], :class => "input is-rounded mb-4" %>

  <%= label_tag :date_start %>
  <%= date_field_tag :date_start, params[:date_start], :class => "input is-rounded mb-4" %>

  <%= label_tag :date_end %>
  <%= date_field_tag :date_end, params[:date_end], :class => "input is-rounded mb-4" %>

  <%= submit_tag "Search", :class => "button is-info" %>
<% end %>
<h1>Calories # of records <%= @calories.count %> </h1>

<table class="table is-striped is-hoverable mx-auto">
  <thead>
    <tr>
      <th>Calories ingested</th>
      <th>Calories burned</th>
      <th>Comment</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calories.each do |calory| %>
      <tr>
        <td><%= calory.calories_ingested %></td>
        <td><%= calory.calories_burned %></td>
        <td><%= calory.comment %></td>
        <td><%= time_ago_in_words(calory.date) %></td>
        <td><%= link_to 'Show', calory %></td>
        <td><%= link_to 'Edit', edit_calory_path(calory) %></td>
        <td><%= link_to 'Destroy', calory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @calories %>
<br>

<%= link_to 'New Calory', new_calory_path, :class => 'button is-primary' %>
</div>

app/views/calories/new.html.erb
<div class="columns content has-text-centered">
<div class="column"></div>
<div class="column is-one-third">
<h1>New Calory</h1>

<%= render 'form', calory: @calory %>

<%= link_to 'Back', calories_path %>
</div>
<div class="column"></div>
</div>

app/views/calories/show.html.erb
<div class="columns content has-text-centered">
<div class="column"></div>
<div class="column is-one-third">

<p>
  <strong>Calories ingested:</strong>
  <%= @calory.calories_ingested %>
</p>

<p>
  <strong>Calories burned:</strong>
  <%= @calory.calories_burned %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @calory.comment %>
</p>

<p>
  <strong>Date:</strong>
  <%= @calory.date %>
</p>

<p>
  <strong>User:</strong>
  <%= @calory.user.email %>
</p>

<%= link_to 'Edit', edit_calory_path(@calory) %> |
<%= link_to 'Back', calories_path %>
</div>
<div class="column"></div>
</div>

app/views/home/dashboard.html.erb
<div class="columns is-vcentered">
  <div class="column is-8">
    <div class="card">
        <div class="card-content">
            <div class="media">
            <div class="media-left">
                <% if @user.avatar.attached? %>
                    <figure class="image is-96x96">
                        <%= image_tag @user.avatar %>
                    </figure>
                <% else %>
                    <figure class="image is-48x48">
                <img src="https://bulma.io/images/placeholders/96x96.png" alt="imagen">
                </figure>
                <% end %>
            </div>
            <div class="media-content">
                <p class="title is-4">
                    <% if @user.first_name? %>
                        <%= @user.full_name %>
                    <% else %>
                        Complete su perfil
                    <% end %>
                </p>
                <p class="subtitle is-6"> <%= @user.email%> </p>
                <% if @user.birthday %>
                    <p class="subtitle is-6"> <strong>Birthday:</strong> <%= @user.birthday.strftime('%B %d') %> </p>
                <% end %>
            </div>
            </div>

            <div class="content">
                <table class="table is-bordered is-striped is-narrow is-hoverable is-small">
                    <thead>
                    </thead>
                    <tbody>
                        <tr>
                            <th>Age</th>
                            <% if @user.birthday? %>
                                <td><%= @user.age %> years</td>
                            <% else %>
                                <td>complete profile</td>
                            <%end%>
                        </tr>
                        <tr>
                            <th>Height</th>
                            <% if @user.height? %>
                                <td><%= @user.height %> m</td>
                            <% else %>
                                <td>complete profile</td>
                            <%end%>
                        </tr>
                         <tr>
                            <th>Weight</th>
                            <% if @user.weight? %>
                                <td><%= @user.weight %> kg</td>
                            <% else %>
                                <td>complete profile</td>
                            <%end%>
                        </tr>
                    </tbody>
                </table>
            Los datos de la grafica comprenden 30 dias de ingesta de calorias y de quema
            de esas mismas dia a dia.
            <br>
            <time> **Last Update for Profile: <%= @user.updated_at %> </time>
            </div>
        </div>
    </div>
  </div>
  <div class="column">
    <div class="card">
    <header class="card-header">
        <p class="card-header-title">
        IMC
        </p>
        <button class="card-header-icon" aria-label="more options">
        <span class="icon">
            <i class="fas fa-check" aria-hidden="true"></i>
        </span>
        </button>
    </header>
    <div class="card-content">
    <div class="content">
      Indice de Masa Corporal
      <p>Formula: <pre>Weight(kg) ÷ (Height (m))^2</pre> </p>
      <% if @user.height? && @user.weight? %>
        <p> <strong><%= @user.imc %></strong> </p>
      <% else %>
        <p> Complete Profile </p>
      <% end %>
    </div>
  </div>
    </div>
  </div>
</div>
<div class="columns">
<%= line_chart @data, download: true %>
</div>

app/views/home/documentation.html.erb
<h1 class="content has-text-centered is-centered">ER Database Kalorias App</h1>

<p class="content has-text-centered is-centered">
    <%= link_to image_tag("kaloria_diagram.svg", alt: "ERD kalorias", class: "") %>
</p>

app/views/home/index.html.erb
<section class="hero is-large is-info">
    <div class="hero-body">
    <p class="title content has-text-centered">
        Welcome <% if user_signed_in? %> 
        <% if current_user.first_name && current_user.last_name %>
            <%= current_user.first_name %> <%= current_user.last_name %>
        <% else %>
            <%= current_user.email %>
        <% end %>
        <% end %>
        to Kalorias
    </p>
    <p class="subtitle content has-text-centered">
        This website is for control your intake <strong>Calories</strong>!
    </p>
    <p>
    <% if user_signed_in? %>
        <div class="buttons is-centered">
            <%= link_to calories_path, class: "button is-warning" do %>
            <span class="icon">
            <i class="fab fa-hotjar"></i>
            </span>
            <span>View all calories</span>
            <% end %>
            <%= link_to new_calory_path, class: "button is-success" do %>
                <span class="icon">
                <i class="fab fa-gulp"></i>
                </span>
                <span>Add new calories</span>
            <% end %>
        </div>
    <% end %>
    </p>
    </div>
</section>

app/views/home/shared_progress.html.erb
<div class="columns content has-text-centered">
<div class="column"></div>
<div class="column is-one-third">
<h2>Compartir mi progreso con alguien más</h2>
<%= form_tag '/sharedp', :method => "get" do%>

Email : </br><%= text_field_tag 'email', '',
:class=> 'input is-info is-rounded mb-4',
:placeholder => "Email" %></br>
<%= submit_tag "submit",:value => "submit", :class => 'button is-primary' %>
<%end%>

</div>
<div class="column"></div>
</div>

app/views/layouts/_footer.html.erb
  <footer class="footer has-text-centered is-flex-align-items-flex-end mt-auto">
      <p>
        <strong>Kalorias</strong> by <a href="#">Carlos Rocha</a>. The source code is hosted in
        <a href="http://opensource.org/licenses/mit-license.php">GitHub</a>.
      </p>
  </footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar is-light is-spaced has-shadow" role="navigation" aria-label="main navigation">
  <div class="navbar-brand is-shadow">
    <a class="navbar-item" href="/">
        <%= link_to image_tag("calorias.png", alt: "kalorias", class: "thumbnail"), "/" %>
    </a>

    <a role="button" class="navbar-burger" id="burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu" id="nav-links">
    <div class="navbar-start">
      <a href="/" class="navbar-item">
        Home
      </a>
      <%= link_to 'Documentation', documentation_path, :class => 'navbar-item' %>
      <% if user_signed_in? %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More actions
        </a>
        <div class="navbar-dropdown">
          <%= link_to 'View all calories', calories_path, :class => 'navbar-item' %>
          <%= link_to 'Add calories', new_calory_path, :class => 'navbar-item' %>
        </div>
      </div>
      <% end %>

    </div>

    <div class="navbar-end">
    <% if user_signed_in? %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          <%= current_user.email %>
        </a>

        <div class="navbar-dropdown">
          <%= link_to 'Dashboard', dashboard_path, :class => 'navbar-item' %>
          <%= link_to 'Shared my progress', sharedp_path, :class => 'navbar-item' %>
          <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-item' %>
          <hr class="navbar-divider">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => 'navbar-item' %>
        </div>
      </div>
    <% else %>
      <div class="navbar-item">
        <div class="buttons">
          <%= link_to 'Sign Up', new_user_registration_path, :class => 'button is-primary' %>
          <%= link_to 'Log In', user_session_path, :class => 'button is-light' %>
        </div>
      </div>
    <% end %>
    </div>

  </div>
</nav>
<% if !current_page?(root_path) %>
<br/><br/>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KaloriaApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container is-fullheight">
      <%= render 'layouts/navbar' %>
      <% if notice %>
        <div class="notification is-success">
          <button class="delete"></button>
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="notification is-danger">
          <button class="delete"></button>
          <%= alert %>
        </div>
      <% end %>
        <% if user_signed_in? %>
          <% if current_user.first_name.blank? || current_user.last_name.blank? || current_user.weight.blank? || current_user.height.blank? || current_user.birthday.blank? %>
            <div class="notification is-warning">
            <button class="delete"></button>
            Edita tu perfil para calcular tu IMC
            y puedas compartir a tus amigos <%= link_to 'Edit profile', edit_user_registration_path %> 
            </div>
          <% end %>
        <% end %>
        <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>